# action.yml
name: 'Maven release'
author: https://github.com/qcastel
description: 'Deploy to another repo by committing over there'
branding:
  color: blue
  icon: unlock
inputs:
  branch-name:
    description: 'The branch to push to'
    required: false
    default: 'master'

  ssh-private-key:
    description: 'The SSH private key used'
    required: false

  git-release-bot-name:
    description: 'The git user name for committing'
    required: false
    default: 'release-bot'
  git-release-bot-email:
    description: 'The git user email for committing'
    required: false
    default: 'release-bot@github.com'



runs:
  using: 'docker'
  image: 'Dockerfile'
  args: 
    - release-github-actions.sh
  env:
    SSH_PRIVATE_KEY: ${{ inputs.ssh-private-key }}
    SSH_ROOT_FOLDER: /root/.ssh

    GIT_RELEASE_BOT_NAME: ${{ inputs.git-release-bot-name }}
    GIT_RELEASE_BOT_EMAIL: ${{ inputs.git-release-bot-email }}

    BRANCH_NAME: ${{ inputs.branch-name }}
